flowchart LR
    DBMS[Database Management System]
    RDBMS[Relational Database Management System]
    DBS[Database System]
    NOSQL[NoSQL Database]
    RD[Relational Database]
    MONGO[MongoDB]
    MYSQL[MySQL]
    PG[PostgreSQL]
    SQL[Structured Query Language]

    DBS --> DBMS
    DBS --> NOSQL
    DBS --> RD
    DBS --> MONGO
    DBS --> MYSQL
    DBS --> PG
    DBS --> SQL
    DBS --> RDBMS

    DBMS --> RDBMS
    DBMS --> MONGO
    RD --> RDBMS
    RD --> SQL

    RDBMS --> MYSQL
    RDBMS --> PG

    NOSQL --> MONGO

    SQL --> MYSQL
    SQL --> PG